const http = require('http');
const url = require('url');
const { CONTENT_JOB_STATES, AGENT_ROLES, BRAND_GUIDELINES } = require('../../packages/shared');
const ContentJobStateMachine = require('../../packages/workflows/state_machine');
const ChiefEditorAgent = require('../../packages/agents/chief_editor_agent');

const PORT = process.env.PORT || 8000;

// In-Memory Storage for First Vertical Slice
const activeJobs = new Map();
const chiefEditor = new ChiefEditorAgent();

// Initialize default sample job
const sampleJob = new ContentJobStateMachine('JOB-2026-001', 'AI Security & Zero-Day Threat Alerts');
activeJobs.set(sampleJob.jobId, sampleJob);

function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Content-Type', 'application/json');
}

const server = http.createServer(async (req, res) => {
  setCorsHeaders(res);

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    return res.end();
  }

  const parsedUrl = url.parse(req.url, true);
  const pathname = parsedUrl.pathname;

  // 1. Health Check
  if (req.method === 'GET' && pathname === '/health') {
    res.writeHead(200);
    return res.end(JSON.stringify({
      status: 'ONLINE',
      platform: 'NCAS Platform API Gateway (Native Zero-Dependency)',
      handle: BRAND_GUIDELINES.handle,
      activeJobsCount: activeJobs.size,
      timestamp: new Date().toISOString()
    }));
  }

  // 2. Niche Strategy Intake (Chief Editor Agent Trigger)
  if (req.method === 'POST' && pathname === '/api/strategy/niche-intake') {
    let bodyData = '';
    req.on('data', chunk => bodyData += chunk);
    req.on('end', async () => {
      try {
        const payload = JSON.parse(bodyData || '{}');
        const { nicheName = 'AI Security 2026', goal = 'Education & Authority', timeframeDays = 30 } = payload;

        const agentReport = await chiefEditor.run({ nicheName, goal, timeframeDays });
        const resultData = agentReport.result || {};
        const editorialPlan = resultData.editorialPlan || {};

        const jobId = `JOB-${Date.now().toString().slice(-6)}`;
        const newJob = new ContentJobStateMachine(jobId, nicheName);
        newJob.transitionTo(CONTENT_JOB_STATES.STRATEGY_REVIEW, 'Chief Editor Agent', {
          editorialPlan: editorialPlan,
          notes: 'Strategy Review Generated'
        });

        activeJobs.set(jobId, newJob);

        res.writeHead(200);
        res.end(JSON.stringify({
          success: true,
          message: `Strategy & 30-Day Editorial Plan Generated by Chief Editor Agent!`,
          jobSummary: newJob.getJobSummary(),
          agentReport: agentReport
        }));
      } catch (err) {
        console.error('Niche Intake Error:', err.message);
        res.writeHead(400);
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
    return;
  }

  // 3. List Content Jobs
  if (req.method === 'GET' && pathname === '/api/jobs') {
    const jobsList = Array.from(activeJobs.values()).map(j => j.getJobSummary());
    res.writeHead(200);
    return res.end(JSON.stringify({ success: true, count: jobsList.length, jobs: jobsList }));
  }

  // 4. List All 22 Agents
  if (req.method === 'GET' && pathname === '/api/agents') {
    const agentsList = Object.entries(AGENT_ROLES).map(([key, name], index) => ({
      id: index + 1,
      key: key,
      name: name,
      status: 'ACTIVE_READY',
      lastHeartbeat: new Date().toISOString()
    }));
    res.writeHead(200);
    return res.end(JSON.stringify({ success: true, count: agentsList.length, agents: agentsList }));
  }

  // Fallback 404
  res.writeHead(404);
  res.end(JSON.stringify({ success: false, error: 'Endpoint not found' }));
});

server.listen(PORT, () => {
  console.log(`\n=============================================================`);
  console.log(` 🚀 NCAS ZERO-DEPENDENCY PLATFORM API GATEWAY RUNNING`);
  console.log(`=============================================================`);
  console.log(`URL:            http://localhost:${PORT}`);
  console.log(`Health Check:   http://localhost:${PORT}/health`);
  console.log(`API Agents:     http://localhost:${PORT}/api/agents`);
  console.log(`Niche Intake:   POST http://localhost:${PORT}/api/strategy/niche-intake\n`);
});
